#!/usr/bin/env python3
"""
CDK Application Entry Point — Voice AI POC-in-a-Box

Deploys the full stack:
  - Pre Stack: Shared infrastructure (S3, ECR, Cognito)
  - Agent Stack: Voice agent runtime (AgentCore WebSocket)
  - Frontend Stack: React UI (CloudFront + S3)
  - Post Stack: Post-deployment configuration
"""

import os
import aws_cdk as cdk

from pre_stack.pre_stack import PreStack
from agent_stack.agent_stack import AgentStack
from demos_stack.demos_stack import DemosStack
from frontend.frontend_stack import FrontendStack
from post_stack.post_stack import PostStack

app = cdk.App()

env = cdk.Environment(
    account=os.environ.get("CDK_DEFAULT_ACCOUNT", os.environ.get("AWS_ACCOUNT_ID")),
    region=os.environ.get("CDK_DEFAULT_REGION", os.environ.get("AWS_DEFAULT_REGION", "us-east-1")),
)

# Shared infrastructure: Cognito, S3, ECR
# SSO Config: pass Federate credentials via CDK context or env vars
# Example: cdk deploy -c federate_client_id=xxx -c federate_client_secret=xxx
federate_client_id = app.node.try_get_context("federate_client_id") or os.environ.get("FEDERATE_CLIENT_ID", "")
federate_client_secret = app.node.try_get_context("federate_client_secret") or os.environ.get("FEDERATE_CLIENT_SECRET", "")
cognito_domain_prefix = app.node.try_get_context("cognito_domain_prefix") or os.environ.get("COGNITO_DOMAIN_PREFIX", "voice-agent-poc")

pre_stack = PreStack(
    app,
    "VoiceAgentPreStack",
    env=env,
    federate_client_id=federate_client_id,
    federate_client_secret=federate_client_secret,
    cognito_domain_prefix=cognito_domain_prefix,
    description="Voice AI POC-in-a-Box: Shared infrastructure (Cognito, S3, ECR)",
)

# Agent runtime: AgentCore with WebSocket support
agent_stack = AgentStack(
    app,
    "VoiceAgentAgentStack",
    env=env,
    pre_stack=pre_stack,
    description="Voice AI POC-in-a-Box: Voice agent runtime (Bedrock AgentCore)",
)
agent_stack.add_dependency(pre_stack)

# Demos API: DynamoDB + Lambda + API Gateway
demos_stack = DemosStack(
    app,
    "VoiceAgentDemosStack",
    env=env,
    agent_stack=agent_stack,
    pre_stack=pre_stack,
    description="Voice AI POC-in-a-Box: Demo configurations CRUD API",
)
demos_stack.add_dependency(agent_stack)

# NOTE: Telephony (PSTN relay) and SIP integration are deployed separately,
# outside this CDK app. They provision internet-facing network infrastructure
# subject to a higher security review bar. See the top-level `telephony/`
# folder (`telephony/pstn/` and `telephony/sip/`) for their source and
# self-managed deployment instructions.

# Frontend: React app served via CloudFront
frontend_stack = FrontendStack(
    app,
    "VoiceAgentFrontendStack",
    env=env,
    pre_stack=pre_stack,
    agent_stack=agent_stack,
    description="Voice AI POC-in-a-Box: Frontend (CloudFront + S3)",
)
frontend_stack.add_dependency(agent_stack)

# Post-deployment: User creation, config injection
post_stack = PostStack(
    app,
    "VoiceAgentPostStack",
    env=env,
    pre_stack=pre_stack,
    description="Voice AI POC-in-a-Box: Post-deployment configuration",
)
post_stack.add_dependency(frontend_stack)

# --- cdk-nag (AWS Solutions checks) ------------------------------------------
# Opt-in security linting of the synthesized templates. Enabled only when the
# `nag` context flag is set, so normal deploys are unaffected:
#   npx cdk synth -c nag=true
# Findings are emitted as annotations during synth (and a report is written to
# cdk.out when verbose is on).
if app.node.try_get_context("nag"):
    from aws_cdk import Aspects
    from cdk_nag import AwsSolutionsChecks, NagSuppressions

    Aspects.of(app).add(AwsSolutionsChecks(verbose=True))

    # Remaining suppressions are limited to findings that are inherent to the CDK
    # framework / AWS-managed constructs or are explicit, documented deployment
    # choices. Substantive findings (S3 TLS+logging, DynamoDB PITR, API Gateway
    # logging+validation, CloudFront TLS+logging, Cognito password policy) are
    # FIXED in the stacks rather than suppressed. See security-scan/cdk-nag-summary.md.
    _framework_suppressions = [
        {"id": "AwsSolutions-IAM4", "reason": "AWSLambdaBasicExecutionRole is the AWS-managed execution role attached by CDK's Lambda/custom-resource constructs; it grants only CloudWatch Logs write. Acceptable managed baseline."},
        {"id": "AwsSolutions-IAM5", "reason": "Wildcards are generated by CDK grant*() helpers (scoped to specific table/bucket ARNs with action-level wildcards) and by CDK-managed constructs (BucketDeployment, custom-resource providers, API Gateway CloudWatch role). The one intentional resource '*' is bedrock:InvokeModel / bedrock-agentcore invoke, which do not support resource-level scoping for on-demand model access."},
        {"id": "AwsSolutions-L1", "reason": "Lambda functions intentionally pin Python 3.12, a current and supported runtime, for reproducible deploys. CDK-managed helper functions (BucketDeployment, CR providers) set their own runtime."},
        {"id": "AwsSolutions-APIG3", "reason": "No WAFv2 web ACL is attached by default: the REST API is protected by a Cognito user-pool authorizer, and WAF is an optional, cost-bearing add-on left to the deployer."},
        {"id": "AwsSolutions-COG2", "reason": "MFA is not forced by default because the reference frontend uses USER_PASSWORD/SRP auth without an MFA challenge UI; operators can enable MFA per their security requirements."},
        {"id": "AwsSolutions-COG8", "reason": "Cognito Plus tier (advanced security features) is a paid, account-level feature plan left to the deployer; not required for the default deployment."},
        {"id": "AwsSolutions-CFR1", "reason": "Geo restriction is a deployment-specific policy choice; the sample distribution serves a globally-available demo UI."},
        {"id": "AwsSolutions-CFR2", "reason": "CloudFront WAF integration is an optional, cost-bearing add-on left to the deployer; the origin is private (OAC) and serves only static assets."},
    ]

    for _stack in (pre_stack, agent_stack, demos_stack, frontend_stack, post_stack):
        NagSuppressions.add_stack_suppressions(_stack, _framework_suppressions, apply_to_nested_stacks=True)

    # Narrow, resource-specific suppressions for two unavoidable cases:
    # 1) CloudFront uses the default *.cloudfront.net certificate, which always
    #    advertises legacy TLS regardless of minimumProtocolVersion (a custom
    #    domain + ACM cert is required to raise it — a deployer choice).
    # 2) The S3 access-log buckets do not themselves have access logging (that
    #    would be circular); this is the standard log-bucket pattern.
    NagSuppressions.add_resource_suppressions_by_path(
        frontend_stack, "/VoiceAgentFrontendStack/WebDistribution/Resource",
        [{"id": "AwsSolutions-CFR4", "reason": "Uses the default CloudFront viewer certificate, which advertises TLSv1 regardless of minimumProtocolVersion. Raising it requires a custom domain + ACM certificate, which is a deployer-specific choice."}],
    )
    for _path in (
        "/VoiceAgentPreStack/AccessLogsBucket/Resource",
        "/VoiceAgentDemosStack/DemosAccessLogsBucket/Resource",
        "/VoiceAgentFrontendStack/FrontendLogsBucket/Resource",
    ):
        _st = {"/VoiceAgentPreStack": pre_stack, "/VoiceAgentDemosStack": demos_stack, "/VoiceAgentFrontendStack": frontend_stack}["/" + _path.split("/")[1]]
        NagSuppressions.add_resource_suppressions_by_path(
            _st, _path,
            [{"id": "AwsSolutions-S1", "reason": "This is the S3 server-access-log destination bucket; enabling access logging on a log bucket would be circular. Standard log-bucket pattern."}],
        )

app.synth()
